import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact | Louis Gallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          💬 Contact
        </h1>

        <p className={styles.description}>
          Let's talk together!
        </p>

        <div className={styles.grid}>
          <a href="mailto:hello@louisgallet.me" className={styles.card}>
            <h2>📨 Mail &rarr;</h2>
            <p>Serious discussion together !</p>
          </a>

          <a href="https://discord.com/app" className={styles.card}>
            <h2>💬 Discord &rarr;</h2>
            <p>To speak in a more relaxed way, my username is @_l0u1$_#5104</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>

          © Louis Gallet - 2021

      </footer>
      <script src="https://s.pageclip.co/v1/pageclip.js" charset="utf-8"></script>
    </div>
    
  )
}
