import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Louis Gallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ✌️ Welcome to the world of <a href="https://louisgallet.me">Louis Gallet</a>
        </h1>

        <p className={styles.description}>
          👨‍💻 A (young) full-stack developer and student from Paris
        </p>

        <div className={styles.grid}>
          <a href="/project" className={styles.card}>
            <h2>📚 Project &rarr;</h2>
            <p>Find all my projects on this page !</p>
          </a>

          <a href="/contact" className={styles.card}>
            <h2>💬 Contact &rarr;</h2>
            <p>Let's talk together!</p>
          </a>

          <a
            href="https://github.com/l0u1sg"
            className={styles.card}
          >
            <h2>🐈 GitHub &rarr;</h2>
            <p>Come and discover my open-source projects</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>

          © Louis Gallet - 2021

      </footer>
    </div>
  )
}
